# Generated by Django 3.2.16 on 2022-10-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20221031_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
